version: "3"
services:
  ldap:
    image: osixia/openldap
    environment:
      LDAP_ORGANISATION: digIT
      LDAP_DOMAIN: chalmers.it
      LDAP_ADMIN_PASSWORD: <ldap_admin_password>
      LDAP_TLS_CRT_FILENAME: live/chalmers.it/cert.pem
      LDAP_TLS_KEY_FILENAME: live/chalmers.it/privkey.pem
      LDAP_TLS_CA_CRT_FILENAME: live/chalmers.it/fullchain.pem
    hostname: chalmers.it
    ports:
      - 636:636
    volumes:
      - /etc/letsencrypt:/container/service/slapd/assets/certs
      - /data/ldap/database:/var/lib/ldap
      - /data/ldap/config:/etc/ldap/slapd.d

  gui:
    image: osixia/phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - 80:80
