version: "3"
services:
  web-proxy:
    image: cthit/caddy-cloudflare:2.3.0
    restart: unless-stopped
    network_mode: host
    environment:
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /data/caddy:/data

  ldap-secure-proxy:
    image: hpello/tcp-proxy:1.1.0
    restart: unless-stopped
    network_mode: host
    command: dantooine.digit-local 636
