version: '3'
services:
  certbot:
    image: certbot/certbot:v1.9.0
    volumes:
      - ${CERTBOT_STORAGE_PATH}/certbot/conf:/etc/letsencrypt
      - ${CERTBOT_STORAGE_PATH}/certbot/www:/var/www/certbot
    command:
      - certonly
      - --preferred-challenges=dns
      - --rsa-key-size=4096
      - --cert-name=${DOMAIN}
      - --domains=${DOMAIN}
      - --domains=*.${DOMAIN}
      - --email=${EMAIL}
      - --manual
      - --force-renewal
      - --agree-tos
      - --no-eff-email
      - --manual-public-ip-logging-ok