version: "3"
services:
  web-proxy:
    image: caddy:2.3.0
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./sites-enabled:/etc/caddy/sites-enabled
      - /data/caddy:/data
      - /var/www:/var/www
