- name: install nginx
  hosts: proxy
  remote_user: digit
  become: yes

  tasks:
    - name: install nginx
      apt:
        name:
          - nginx
        state: latest
        update_cache: yes
    - name: enable nginx service
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: yes
