- name: install certbot
  hosts: proxy
  remote_user: digit
  become: yes

  tasks:
    - name: install certs
      ansible.builtin.shell: |
        certbot certonly \
          --dns-cloudflare \
          --dns-cloudflare-credentials ~/.secrets/certbot/cloudflare.ini \
          --dns-cloudflare-propagation-seconds 60 \
          --email serverchef.digit@chalmers.it \
          --rsa-key-size=4096 \
          --cert-name=chalmers.it \
          --domains=chalmers.it \
          --domains=*.chalmers.it \
          --domains=nollk.it \
          --agree-tos \
          --no-eff-email \
          --manual-public-ip-logging-ok
