- name: install certbot
  hosts: proxy
  remote_user: digit
  become: yes

  tasks:
    - name: install chalmers.it cert
      ansible.builtin.shell: |
        certbot certonly \
          --dns-cloudflare \
          --dns-cloudflare-credentials /home/digit/.secrets/certbot/cloudflare.ini \
          --dns-cloudflare-propagation-seconds 60 \
          --email serverchef.digit@chalmers.it \
          --rsa-key-size=4096 \
          --cert-name=chalmers.it \
          --domains=chalmers.it \
          --domains=*.chalmers.it \
          --agree-tos \
          --no-eff-email \
          --non-interactive
    - name: stop nginx service
      ansible.builtin.systemd:
        name: nginx
        state: stopped
    - name: install nollk.it cert
      ansible.builtin.shell: |
        certbot certonly \
          --standalone \
          --email serverchef.digit@chalmers.it \
          --rsa-key-size=4096 \
          --cert-name=nollk.it \
          --domains=nollk.it \
          --agree-tos \
          --no-eff-email \
          --non-interactive
    - name: start nginx service
      ansible.builtin.systemd:
        name: nginx
        state: started
