- name: install certs
  hosts: proxy
  remote_user: digit
  become: yes

  tasks:
    - name: install certbot
      community.general.snap:
        name: certbot
        classic: yes
    - name: symlink certbot to /usr/bin
      ansible.builtin.file:
        src: /snap/bin/certbot
        dest: /usr/bin/certbot
        owner: root
        group: root
        state: link
    - name: trust certbot with root
      ansible.builtin.shell: sudo snap set certbot trust-plugin-with-root=ok
    - name: install certbot cloudflare plugin
      community.general.snap:
        name: certbot-dns-cloudflare
