- name: install qemu-guest-agent
  hosts: ubuntu
  remote_user: digit-local
  become: yes

  tasks:
    - name: install
      apt:
        name: qemu-guest-agent
        state: latest
        update_cache: yes
